import React, { useEffect, useState } from 'react';
import { PageShell } from '../components/layout';
import { Card, StatusMessage } from '../components/ui';
import { apiRequest } from '../services/api';

export default function ProfilePage() {
  const [profile, setProfile] = useState(null); const [visits, setVisits] = useState([]); const [loading, setLoading] = useState(true); const [status, setStatus] = useState({ type: '', message: '' });
  useEffect(() => { apiRequest('/auth/me').then((data) => { if (data.success) setProfile(data.user); }).catch((err) => setStatus({ type: 'error', message: err.message })).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (profile?.role !== 'PATIENT') return; apiRequest('/patient/visits').then((data) => setVisits(data.visits || [])).catch((err) => console.error('Error loading patient visits:', err)); }, [profile?.role]);
  const handleUpdate = async (e) => { e.preventDefault(); setStatus({ type: '', message: '' }); try { await apiRequest('/auth/profile', { method: 'PUT', body: JSON.stringify({ full_name: profile.full_name, email: profile.email, phone: profile.phone }) }); setStatus({ type: 'success', message: 'Profile details updated successfully!' }); } catch (err) { setStatus({ type: 'error', message: err.message }); } };
  if (loading) return <PageShell title="Your Profile" bottomNavIndex={3}><div className="center-message">Loading profile details...</div></PageShell>;
  const initial = profile.full_name?.trim().charAt(0).toUpperCase() || 'P';
  return <PageShell title="Your Profile" bottomNavIndex={3}>{status.message && <StatusMessage type={status.type}>{status.message}</StatusMessage>}<Card className="profile-card mb-4"><span className="profile-avatar">{initial}</span><div><h2>{profile.full_name}</h2><p>{profile.role?.replace('_', ' ')} â€¢ {profile.email}</p></div></Card>{profile.role === 'PATIENT' && <Card className="mb-4"><h3 className="mb-3">Visit History</h3>{visits.length === 0 ? <p className="text-muted mb-0">No visits have been recorded yet.</p> : <div className="d-flex flex-column gap-2">{visits.map((visit) => <div key={visit.visit_id} className="border rounded p-3"><div className="d-flex justify-content-between gap-3 flex-wrap"><strong>{new Date(visit.visit_date).toLocaleString()}</strong><span className="text-muted">Added by {visit.created_by_name}</span></div><p className="mb-0 mt-2">{visit.description}</p></div>)}</div>}</Card>}<Card><h3 className="mb-3">Edit Profile Details</h3><form onSubmit={handleUpdate} className="row g-3">{[['Full Name', 'text', 'full_name'], ['Email Address', 'email', 'email'], ['Phone Contact', 'text', 'phone']].map(([label, type, key]) => <div className="col-12" key={key}><label className="form-label">{label}</label><input type={type} className="form-control" value={profile[key] || ''} onChange={(e) => setProfile({ ...profile, [key]: e.target.value })} required /></div>)}<div className="col-12 text-end mt-3"><button type="submit" className="primary-btn" style={{ width: 'auto', padding: '0 24px' }}>Save Changes</button></div></form></Card></PageShell>;
}
